#define N_DESAFIOS 2 //QUANTIDADE DE DESAFIOS A SEREM REALIZADOS

typedef struct
{
  /*
     Estados                             AC AL AM AP BA CE DF ES GO MA MG MS MT PA PB PE PI PR RJ RN RO RR RS SC SE SP TO
     Numero                               0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26
     VARIAVEL #VAR_01 PARA REPRESENTAR A CONFGURACAO DO ESTADO DO CANDIDATO
     DEVE SER PREENCHIDA NO DESAFIO 01
  */
#VAR_01

  /*
     VARIAVEL #VAR_02 PARA SALVAR O PRIMEIRO NOME DO CANDIDATO
     DEVE SER PREENCHINA NO DESAFIO 01
  */
#VAR_02

  struct
  {
    /*
       VARIAVEL #VAR_03 DEVE SER UM BOOLEANO PARA SALVAR O DIA DA SEMANA QUE FOI ENVIADO O DESAFIO
       SEGUINDO O PADRAO DE DIAS> DOMINGO, SEGUNDA, TERCA, QUARTA, QUINTA, SEXTA, SABADO
       DEVE SER PREENCHIDA NO DESAFIO 01
    */
    bool #VAR_03
  } diasDaSemana[/*DEFINIR O TAMANHO DO VETOR DA SEMANA*/];

  struct
  {
    /*
       VARIAVEL #VAR_04 PARA HORA DO DIA E #VAR_05 PARA MINUTO DA HORA => EX(10:58, 14:30).
       PREENCHA OS PADROES DE ACIONAMENTO A SEU CRITERIO.
       ESSAS VARIAVEIS SERA UTILIZADA NO DESAFIO 01 e 02
    */
#VAR_04
#VAR_05
  } acionamentos[/*DEFINIR O TAMANHO DO VETOR PARA 5 ACIONAMENTOS*/];
} desafios_t;

struct
{
  /*
    ESTRUTURA PARA SALVAR O SSID E A SENHA DO WIFI PARA UTILIZAR NO EXERCICIO 2
    #VAR_06
    #VAR_07
  */
#VAR_06
#VAR_07
} setupWiFi;

desafios_t desafios[N_DESAFIOS];

void setup()
{

}

void loop()
{

}
